Part4c.md translated to ptbr
mayconblopes/fullstack-hy2020.github.io pull request #2
Opened 2023-03-14 19:35 UTC by jccallves

Chapter 4, letter c translated to Brazilian Portuguese.
Sending for review.

2023-03-14 22:54 UTC, mayconblopes commented on README.md
> +
Add your github, @jccallves

2023-03-14 22:54 UTC, mayconblopes commented on README.md
> +- [ ] part4c
Mark part4c as completed, @jccallves

2023-03-14 23:18 UTC, mayconblopes commented on src/content/4/ptbr/part4c.md
> +Você pode encontrar o código de nosso aplicativo atual na íntegra na ramificação <i>part4-8</i> [deste repositório GitHub](https://github.com/fullstack-hy2020/part3-notes-backend/tree/part4-8).
### para manter coerência com traduções já feitas:
Você pode encontrar o código de ~nosso aplicativo~ nossa aplicação atual

2023-03-14 23:18 UTC, mayconblopes commented on src/content/4/ptbr/part4c.md
> +Tradicionalmente, os bancos de dados de documentos, como o Mongo, não oferecem suporte a <i>consultas de junção</i> que estão disponíveis em bancos de dados relacionais, usados ​​para agregar dados d
@jccallves , alguns termos que são muito conhecidos no mundo dev, nós estamos optando por manter em inglês. 
Estou um pouco na dúvida sobre  "consultas de junção". Seria melhor deixar "join queries"? O que você acha?

2023-03-16 11:30 UTC, jccallves commented
Bom dia, Maycon
Sem dúvidas join queries seria melhor, no momento da tradução fiquei na
dúvida se traduzia ou mantinha o termo, estava mais propenso a deixar o
inglês, mas preferi traduzir e receber o feedback.

Nas próximas traduções então, mantenho os termos mais conhecidos.

Att,

Em ter., 14 de mar. de 2023 20:18, Maycon B. Lopes ***@***.***>
escreveu:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In src/content/4/ptbr/part4c.md
> <https://github.com/mayconblopes/fullstack-hy2020.github.io/pull/2#discussion_r1136330099>
> :
>
> > +```js
> +const noteSchema = new mongoose.Schema({
> +  content: {
> +    type: String,
> +    required: true,
> +    minlength: 5
> +  },
> +  important: Boolean,
> +  user: {
> +    type: mongoose.Schema.Types.ObjectId,
> +    ref: 'User'
> +  }
> +})
> +```
> +
> +Você pode encontrar o código de nosso aplicativo atual na íntegra na ramificação <i>part4-8</i> [deste repositório GitHub](https://github.com/fullstack-hy2020/part3-notes-backend/tree/part4-8).
>
> para manter coerência com traduções já feitas:
>
> Você pode encontrar o código de nosso aplicativo nossa aplicação atual
> ------------------------------
>
> In src/content/4/ptbr/part4c.md
> <https://github.com/mayconblopes/fullstack-hy2020.github.io/pull/2#discussion_r1136340557>
> :
>
> > +
> +Queremos adicionar autenticação e autorização do usuário ao nosso aplicativo. Os usuários devem ser armazenados no banco de dados e cada nota deve ser vinculada ao usuário que a criou. Excluir e editar uma nota só deve ser permitido para o usuário que a criou.
> +
> +Vamos começar adicionando informações sobre usuários ao banco de dados. Existe uma relação um-para-muitos entre o usuário (<i>Usuário</i>) e as notas (<i>Nota</i>):
> +
> +![diagrama ligando usuário e notas](https://yuml.me/a187045b.png)
> +
> +Se estivéssemos trabalhando com um banco de dados relacional, a implementação seria direta. Ambos os recursos teriam suas tabelas de banco de dados separadas e o id do usuário que criou uma nota seria armazenado na tabela notas como uma chave estrangeira.
> +
> +Ao trabalhar com bancos de dados de documentos, a situação é um pouco diferente, pois há muitas maneiras diferentes de modelar a situação.
> +
> +A solução existente salva cada nota na <i>coleção de notas</i> no banco de dados. Se não quisermos alterar essa coleção existente, a escolha natural é salvar os usuários em sua própria coleção, <i>usuários<i> por exemplo.
> +
> +Como em todos os bancos de dados de documentos, podemos usar IDs de objeto no Mongo para fazer referência a documentos em outras coleções. Isso é semelhante ao uso de chaves estrangeiras em bancos de dados relacionais.
> +
> +Tradicionalmente, os bancos de dados de documentos, como o Mongo, não oferecem suporte a <i>consultas de junção</i> que estão disponíveis em bancos de dados relacionais, usados ​​para agregar dados de várias tabelas. No entanto, a partir da versão 3.2, o Mongo oferece suporte a [consultas de agregação de pesquisa](https://docs.mongodb.com/manual/reference/operator/aggregation/lookup/). Não veremos essa funcionalidade neste curso.
>
> @jccallves <https://github.com/jccallves> , alguns termos que são muito
> conhecidos no mundo dev, nós estamos optando por manter em inglês.
> Estou um pouco na dúvida sobre "consultas de junção". Seria melhor deixar
> "join queries"? O que você acha?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/mayconblopes/fullstack-hy2020.github.io/pull/2#pullrequestreview-1340411037>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AFBZCX5E37O2UDM43QWJQALW4D4FVANCNFSM6AAAAAAV24COKU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***
> com>
>

2023-03-18 00:03 UTC, mayconblopes commented on src/content/4/ptbr/part4c.md
> +Se estivéssemos usando um banco de dados relacional, a nota conteria uma <i>chave de referência</i> para o usuário que a criou. Em bancos de dados de documentos, podemos fazer a mesma coisa.
Vi que no original também está escrito "reference key". Mesmo assim, o correto não seria chave estrangeira?
Chave de referência não me parece um termo muito conhecido.

2023-03-18 11:48 UTC, mayconblopes commented on src/content/4/ptbr/part4c.md
> +Neste caso, decidimos armazenar os ids das notas criadas pelo usuário no documento do usuário. Vamos definir o modelo para representar um usuário no arquivo <i>models/user.js</i>:
(...) armazenar os ids das notas criadas pelo usuário no documento ~do usuário~ user (...)

2023-03-18 12:15 UTC, mayconblopes requested changes
@jccallves, sua tradução está muito boa. Fiz a revisão completa e apontei alguns pequenos ajustes, a maioria apenas para manter coerência com as demais traduções já feitas.

2023-03-18 12:15 UTC, mayconblopes commented on src/content/4/ptbr/part4c.md
> +Neste caso, decidimos armazenar os ids das notas criadas pelo usuário no documento do usuário. Vamos definir o modelo para representar um usuário no arquivo <i>models/user.js</i>:
(...) armazenar os ids das notas criadas pelo usuário no documento ~do usuário~ _user_ (...)

2023-03-18 12:15 UTC, mayconblopes commented on src/content/4/ptbr/part4c.md
> +Os ids das notas são armazenados no documento do usuário como uma matriz de ids do Mongo. A definição é a seguinte:
(...) no documento ~do usuário~ _user_ (...)

2023-03-18 12:15 UTC, mayconblopes commented on src/content/4/ptbr/part4c.md
> +Vamos supor que a coleção de <i>usuários</i> contém dois usuários:
Vamos supor que a coleção de ~<i>usuários</i>~ <i>users</i> contém dois usuários:

2023-03-18 12:15 UTC, mayconblopes commented on src/content/4/ptbr/part4c.md
> +A coleção <i>notas</i> contém três notas, que todas elas tem um campo de <i>usuário</i> que faz referência a um usuário na coleção de <i>usuários</i>:
A coleção ~<i>notas</i>~ <i>notes</i> contém três notas, ~que~ todas elas ~tem~ com um campo ~de <i>usuário</i>~ <i>user</i> que faz referência a um usuário na coleção ~de <i>usuários</i>~ <i>users</i>:

2023-03-18 12:15 UTC, mayconblopes commented on src/content/4/ptbr/part4c.md
> +Os bancos de dados de documentos não exigem que a chave estrangeira seja armazenada nos recursos de nota, ela <i>também</i> pode ser armazenada na coleção de usuários ou até mesmo em ambos:
(...) na coleção ~de usuários~ users (...)

2023-03-18 12:15 UTC, mayconblopes commented on src/content/4/ptbr/part4c.md
> +Como os usuários podem ter muitas notas, os IDs relacionados são armazenados em uma matriz no campo de <i>notas</i>.
(...) no campo ~de <i>notas</i>~ <i>notes</i> (...)

2023-03-18 12:15 UTC, mayconblopes commented on src/content/4/ptbr/part4c.md
> +Os bancos de dados de documentos também oferecem uma maneira radicalmente diferente de organizar os dados: em algumas situações, pode ser benéfico aninhar todo o array de notas como parte dos documen
(...) como parte dos documentos na coleção ~de usuários~ users:

2023-03-18 12:15 UTC, mayconblopes commented on src/content/4/ptbr/part4c.md
> +O tipo do campo é <i>ObjectId</i> que faz referência a documentos de estilo de <i>nota</i>. O Mongo não sabe inerentemente que este é um campo que faz referência a notas, a sintaxe é puramente relaci
(...) que faz referência a documentos ~de estilo de <i>nota</i>~ do estilo <i>Note</i>

2023-03-18 12:15 UTC, mayconblopes commented on src/content/4/ptbr/part4c.md
> +Vamos implementar uma rota para criar novos usuários. Os usuários têm um <i>nome de usuário</i> exclusivo, um nome e algo chamado <i>passwordHash</i>. O hash da senha é a saída de uma  [função hash u
Os usuários têm um ~<i>nome de usuário</i>~ <i>username</i> exclusivo, um <i>name</i> (nome) e algo chamado <i>passwordHash</i>

2023-03-18 12:15 UTC, mayconblopes commented on src/content/4/ptbr/part4c.md
> +A criação de novos usuários ocorre em conformidade com as convenções RESTful discutidas na [part 3](/ptbr/part3/node_js_and_express#rest), fazendo uma solicitação HTTP POST para o caminho do <i>usuár
(...) discutidas na ~[part 3]~ [parte 3] (...) 

(...) fazendo uma solicitação HTTP POST para o caminho ~do <i>usuário</i>~ <i>users</i>.

2023-03-18 12:15 UTC, mayconblopes commented on src/content/4/ptbr/part4c.md
> +Você pode encontrar o código da nossa aplicação atual na íntegra na ramificação <i>part4-7</i> [deste repositório GitHub](https://github.com/fullstack-hy2020/part3-notes-backend/tree/part4-7).
na ~ramificação~ branch

2023-03-18 13:37 UTC, jccallves commented
@mayconblopes alterações comitadas.

2023-03-18 14:41 UTC, merged