Tradução dos arquivos part5.md e part5a.md
mayconblopes/fullstack-hy2020.github.io pull request #3
Opened 2023-03-17 22:41 UTC by FrancisBernard34

Peço a revisão da tradução e, caso haja algum termo incorreto, um esclarecimento dos termos corretos a serem utilizados para que eu possa corrigi-los e alinhar melhor nas próximas traduções.

2023-03-20 23:32 UTC, mayconblopes commented on src/content/5/ptbr/part5.md
Tudo certo!

2023-03-21 00:00 UTC, mayconblopes requested changes
@FrancisBernard34, sua tradução está muito boa! Seguem algumas melhorias.
Obrigado.

2023-03-21 00:00 UTC, mayconblopes commented on src/content/5/ptbr/part5a.md
> +Um [truque](https://reactjs.org/docs/conditional-rendering.html#inline-if-with-logical--operator) um pouco estranho, mas comumente usado no React, é usado para renderizar os formulários condicionalme
alterar o link do material extra para documentação em ptbr:

https://pt-br.reactjs.org/docs/conditional-rendering.html#inline-if-with-logical--operator

2023-03-21 00:00 UTC, mayconblopes commented on src/content/5/ptbr/part5a.md
> +Valores salvos no armazenamento são [DOMstrings](https://docs.w3cub.com/dom/domstring), então não podemos salvar um objeto JavaScript da forma como ele é. O objeto deve ser convertido para JSON prime
@FrancisBernard34 , veja se esta substituição ficaria melhor:
~Correspondentemente~ Da mesma forma, quando um objeto (...)

2023-03-21 00:00 UTC, mayconblopes commented on src/content/5/ptbr/part5a.md
> +O jeito certo de fazer isso é com um [hook de efeito](https://pt-br.reactjs.org/docs/hooks-effect.html): um mecanismo que conhecemos pela primeira vez na [parte 2](/en/part2/getting_data_from_server#
Substituir o link "/en/part2/getting_data_from_server#effect-hooks" para o correspondente à versão ptbr do curso.

2023-03-21 00:00 UTC, mayconblopes commented on src/content/5/ptbr/part5a.md
> +No [fim](/en/part4/token_authentication#problems-of-token-based-authentication) da última parte, nós mencionamos que o desafio da autenticação baseada em token é como lidar com a situação em que o ac
Também substituir este link "/en/part4/token_authentication#problems-of-token-based-authentication" pela versão ptbr.

2023-03-21 10:50 UTC, FrancisBernard34 commented on src/content/5/ptbr/part5a.md
> +Um [truque](https://reactjs.org/docs/conditional-rendering.html#inline-if-with-logical--operator) um pouco estranho, mas comumente usado no React, é usado para renderizar os formulários condicionalme
Link atualizado.

2023-03-21 10:51 UTC, FrancisBernard34 commented on src/content/5/ptbr/part5a.md
> +Valores salvos no armazenamento são [DOMstrings](https://docs.w3cub.com/dom/domstring), então não podemos salvar um objeto JavaScript da forma como ele é. O objeto deve ser convertido para JSON prime
Ficou bem melhor @mayconblopes , obrigado pela sugestão!

2023-03-21 10:51 UTC, FrancisBernard34 commented on src/content/5/ptbr/part5a.md
> +O jeito certo de fazer isso é com um [hook de efeito](https://pt-br.reactjs.org/docs/hooks-effect.html): um mecanismo que conhecemos pela primeira vez na [parte 2](/en/part2/getting_data_from_server#
Link atualizado.

2023-03-21 10:51 UTC, FrancisBernard34 commented on src/content/5/ptbr/part5a.md
> +No [fim](/en/part4/token_authentication#problems-of-token-based-authentication) da última parte, nós mencionamos que o desafio da autenticação baseada em token é como lidar com a situação em que o ac
Link atualizado.

2023-03-22 00:08 UTC, mayconblopes approved these changes
Ótimo!
Pronto para merge.

2023-03-22 00:09 UTC, merged